apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-lab-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kube-lab-app
  template:
    metadata:
      labels:
        app: kube-lab-app
    spec:
      containers:
      - name: kube-lab-app
        image: kube-lab-app:v2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        # OPTIONAL: add liveness/readiness later for challenges
